/**
 * Build script to bundle markdown pages into the worker
 * This reads all .md files from src/frontend/public/pages and creates
 * a TypeScript module that can be imported by the worker
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PAGES_DIR = path.join(__dirname, '../../../src/frontend/public/pages');
const OUTPUT_FILE = path.join(__dirname, '../lib/bundled-pages.js');
const OUTPUT_DTS = path.join(__dirname, '../lib/bundled-pages.d.ts');

interface PageManifest {
  [slug: string]: string;
}

function main(): void {
  console.log('[BUILD PAGES] Starting pages bundling...');
  console.log('[BUILD PAGES] Pages directory:', PAGES_DIR);
  console.log('[BUILD PAGES] Output file:', OUTPUT_FILE);

  if (!fs.existsSync(PAGES_DIR)) {
    console.error(`[BUILD PAGES] ERROR: Pages directory not found: ${PAGES_DIR}`);
    process.exit(1);
  }

  const manifest: PageManifest = {};
  const files = fs.readdirSync(PAGES_DIR);
  
  console.log(`[BUILD PAGES] Found ${files.length} files`);

  for (const file of files) {
    if (!file.endsWith('.md')) {
      console.log(`[BUILD PAGES] Skipping non-markdown file: ${file}`);
      continue;
    }

    const slug = file.replace('.md', '');
    const filePath = path.join(PAGES_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    
    manifest[slug] = content;
    console.log(`[BUILD PAGES] Bundled: ${slug} (${content.length} bytes)`);
  }

  // Generate JavaScript module (not TypeScript)
  const output = `/**
 * Auto-generated file containing bundled page content
 * DO NOT EDIT MANUALLY - Generated by scripts/build-pages.ts
 * 
 * Run: npm run build:pages to regenerate
 */

export const BUNDLED_PAGES = ${JSON.stringify(manifest, null, 2)};

export const PAGE_COUNT = ${Object.keys(manifest).length};
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  
  // Generate type declaration file
  const dtsContent = `/**
 * Type declarations for bundled-pages.js
 * Auto-generated file - do not edit manually
 */

export const BUNDLED_PAGES: Record<string, string>;
export const PAGE_COUNT: number;
`;
  fs.writeFileSync(OUTPUT_DTS, dtsContent, 'utf-8');
  
  console.log('[BUILD PAGES] ✓ Successfully bundled pages:');
  console.log(`[BUILD PAGES]   - ${Object.keys(manifest).length} pages`);
  console.log(`[BUILD PAGES]   - Output: ${OUTPUT_FILE}`);
  console.log('[BUILD PAGES]   - Pages:', Object.keys(manifest).sort().join(', '));
}

main();
