// This file is auto-generated by scripts/bundle-templates.ts
// DO NOT EDIT MANUALLY - Your changes will be overwritten
// To update templates, edit files in src/workers/templates/social-media/*.txt
// Then run: npm run bundle:templates

export const BUNDLED_TEMPLATES: Record<string, string> = {
  "bluesky": "{{title}}{{#if artist}} by {{artist}}{{/if}}\r\n\r\n{{#if location}}📍 {{location}}{{/if}}\r\n{{#if year}}📅 {{year}}{{/if}}\r\n\r\n{{#if description}}\r\n{{description}}\r\n{{/if}}\r\n\r\nMore information: {{url}}\r\n\r\n#PublicArt #UrbanArt #Art {{#if location}}#{{location}}{{/if}} {{#if location}}#{{tag:artwork_type}}{{/if}} {{#if keywords}}#{{keywords}}{{/if}}",
  "instagram": "{{title}}{{#if artist}} by {{artist}}{{/if}}\r\n\r\n{{#if location}}📍 {{location}}{{/if}}\r\n{{#if year}}📅 {{year}}{{/if}}\r\n\r\n{{#if description}}\r\n{{description}}\r\n{{/if}}\r\n\r\nMore information: {{url}}\r\n\r\n#PublicArt #UrbanArt #Art {{#if location}}#{{location}}{{/if}} {{#if location}}#{{artwork_type}}{{/if}} {{#if keywords}}#{{keywords}}{{/if}}"
};
