/**
 * Build script to bundle social media templates into TypeScript
 * Run this before deploying: npm run bundle:templates
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const templatesDir = path.resolve(__dirname, '../src/workers/templates/social-media');
const outputFile = path.resolve(__dirname, '../src/workers/lib/social-media/bundled-templates.generated.ts');

const platforms = ['bluesky', 'instagram', 'twitter', 'facebook'];

console.log('📦 Bundling social media templates...\n');

const templates: Record<string, string> = {};

for (const platform of platforms) {
  const templatePath = path.join(templatesDir, `${platform}.txt`);
  
  if (fs.existsSync(templatePath)) {
    const content = fs.readFileSync(templatePath, 'utf8');
    templates[platform] = content;
    console.log(`✅ Loaded ${platform}.txt (${content.length} chars)`);
  } else {
    console.log(`⚠️  Skipped ${platform}.txt (not found)`);
  }
}

// Generate TypeScript file
const tsContent = `// This file is auto-generated by scripts/bundle-templates.ts
// DO NOT EDIT MANUALLY - Your changes will be overwritten
// To update templates, edit files in src/workers/templates/social-media/*.txt
// Then run: npm run bundle:templates

export const BUNDLED_TEMPLATES: Record<string, string> = ${JSON.stringify(templates, null, 2)};
`;

fs.writeFileSync(outputFile, tsContent, 'utf8');

console.log(`\n✅ Generated ${outputFile}`);
console.log(`📝 Bundled ${Object.keys(templates).length} templates\n`);
